import type { AgentEdge, AgentModule, PlotverseData } from "@/lib/types";
import { todayIso } from "@/lib/utils";

const now = todayIso();

export const realEstateModules: AgentModule[] = [
  {
    id: "mod_property_normalizer",
    key: "property-normalizer",
    label: "Property Normalizer",
    description: "Turns messy property notes into comparable structured attributes.",
    inputSchema: "Raw property record",
    outputSchema: "Normalized area, budget band, amenities, caveats",
    promptSummary: "Extract location, type, commercial facts, lifestyle signals, and missing data.",
    x: 40,
    y: 100,
  },
  {
    id: "mod_client_normalizer",
    key: "client-normalizer",
    label: "Client Preference Normalizer",
    description: "Converts client notes into constraints, preferences, and deal risks.",
    inputSchema: "Client profile and notes",
    outputSchema: "Budget, preferred areas, must-haves, blockers, urgency",
    promptSummary: "Separate hard constraints from soft preferences and infer open questions.",
    x: 40,
    y: 300,
  },
  {
    id: "mod_rule_matcher",
    key: "rule-matcher",
    label: "Rule Matcher",
    description: "Applies deterministic budget, area, type, bedroom, and size filters.",
    inputSchema: "Normalized property + normalized client",
    outputSchema: "Pass/fail, score baseline, reasons, warnings",
    promptSummary: "No LLM. This module keeps matching grounded in explicit facts.",
    x: 340,
    y: 200,
  },
  {
    id: "mod_fit_analyst",
    key: "fit-analyst",
    label: "Fit Analyst",
    description: "Explains why a passing match is compelling or weak.",
    inputSchema: "Rule match result plus source records",
    outputSchema: "Fit summary, confidence, buying angle",
    promptSummary: "Write a concise advisor-style explanation for a real estate operator.",
    x: 650,
    y: 120,
  },
  {
    id: "mod_objection_finder",
    key: "objection-finder",
    label: "Objection Finder",
    description: "Surfaces likely objections before outreach.",
    inputSchema: "Fit analysis and raw notes",
    outputSchema: "Objection list and questions to clarify",
    promptSummary: "Look for budget stretch, location mismatch, missing amenities, and timing risk.",
    x: 650,
    y: 310,
  },
  {
    id: "mod_draft_writer",
    key: "draft-writer",
    label: "Outreach Draft Writer",
    description: "Creates a human-approved WhatsApp/email/call draft.",
    inputSchema: "Match, fit summary, objections",
    outputSchema: "Draft copy and suggested tone",
    promptSummary: "Draft only. Never claim a message was sent.",
    x: 960,
    y: 190,
  },
  {
    id: "mod_approval_gate",
    key: "approval-gate",
    label: "Approval Gate",
    description: "Requires your review before anything leaves the system.",
    inputSchema: "Draft message",
    outputSchema: "Pending, approved, rejected, or edited",
    promptSummary: "Human approval is mandatory for every outbound action.",
    x: 1260,
    y: 190,
  },
  {
    id: "mod_reporter",
    key: "run-reporter",
    label: "Run Reporter",
    description: "Persists run logs, step outputs, and audit trail.",
    inputSchema: "All module results",
    outputSchema: "Run summary and trace",
    promptSummary: "Summarize what happened and preserve enough context to debug it.",
    x: 1560,
    y: 190,
  },
];

export const realEstateEdges: AgentEdge[] = [
  { id: "edge_property_rule", source: "mod_property_normalizer", target: "mod_rule_matcher", label: "property facts" },
  { id: "edge_client_rule", source: "mod_client_normalizer", target: "mod_rule_matcher", label: "client constraints" },
  { id: "edge_rule_fit", source: "mod_rule_matcher", target: "mod_fit_analyst", label: "passed candidates" },
  { id: "edge_rule_objections", source: "mod_rule_matcher", target: "mod_objection_finder", label: "warnings" },
  { id: "edge_fit_draft", source: "mod_fit_analyst", target: "mod_draft_writer", label: "positioning" },
  { id: "edge_objection_draft", source: "mod_objection_finder", target: "mod_draft_writer", label: "risks" },
  { id: "edge_draft_approval", source: "mod_draft_writer", target: "mod_approval_gate", label: "draft" },
  { id: "edge_approval_report", source: "mod_approval_gate", target: "mod_reporter", label: "audit event" },
];

export const seedData: PlotverseData = {
  properties: [
    {
      id: "prop_bandstand_01",
      title: "Sea-facing Bandstand apartment",
      address: "Bandstand Promenade",
      area: "Bandra West",
      city: "Mumbai",
      propertyType: "Apartment",
      price: 82000000,
      sizeSqft: 1450,
      bedrooms: 3,
      bathrooms: 3,
      status: "active",
      amenities: ["Sea view", "Parking", "Gym", "Security"],
      notes: "Premium finish, immediate possession, seller prefers clean payment schedule.",
      source: "manual seed",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prop_khar_02",
      title: "Quiet Khar duplex",
      address: "16th Road",
      area: "Khar West",
      city: "Mumbai",
      propertyType: "Duplex",
      price: 122000000,
      sizeSqft: 2450,
      bedrooms: 4,
      bathrooms: 4,
      status: "active",
      amenities: ["Private terrace", "Two parking", "Low density building"],
      notes: "Excellent for family buyer, needs light renovation in kitchen.",
      source: "manual seed",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "prop_powai_03",
      title: "Lake district investment flat",
      address: "Hiranandani Gardens",
      area: "Powai",
      city: "Mumbai",
      propertyType: "Apartment",
      price: 38500000,
      sizeSqft: 980,
      bedrooms: 2,
      bathrooms: 2,
      status: "active",
      amenities: ["Clubhouse", "Rental demand", "Pool"],
      notes: "Tenant occupied for six months, good rental yield profile.",
      source: "manual seed",
      createdAt: now,
      updatedAt: now,
    },
  ],
  clients: [
    {
      id: "client_mehra_01",
      name: "Riya Mehra",
      contact: "WhatsApp preferred",
      budgetMin: 65000000,
      budgetMax: 90000000,
      preferredAreas: ["Bandra West", "Khar West"],
      propertyType: "Apartment",
      minBedrooms: 3,
      minSizeSqft: 1200,
      mustHaves: ["Parking", "Security", "Good light"],
      dealBlockers: ["Long possession", "No parking"],
      urgency: "high",
      notes: "Wants something polished, shortlisting this week for family relocation.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "client_iyer_02",
      name: "Arjun Iyer",
      contact: "Email first, call after shortlist",
      budgetMin: 30000000,
      budgetMax: 45000000,
      preferredAreas: ["Powai", "Vikhroli"],
      propertyType: "Apartment",
      minBedrooms: 2,
      minSizeSqft: 850,
      mustHaves: ["Rental demand", "Clubhouse"],
      dealBlockers: ["Major renovation"],
      urgency: "medium",
      notes: "Investment buyer, prioritizes yield and low maintenance.",
      createdAt: now,
      updatedAt: now,
    },
  ],
  matches: [],
  draftMessages: [],
  agentModules: realEstateModules,
  agentEdges: realEstateEdges,
  agentRuns: [],
  agentRunSteps: [],
  csvImports: [],
};
