import type { AgentEdge, AgentModule, PlotverseData, ScrapeSource } from "@/lib/types";
import { todayIso } from "@/lib/utils";

const now = todayIso();

export const realEstateModules: AgentModule[] = [
  {
    id: "mod_property_normalizer",
    key: "property-normalizer",
    label: "Property Normalizer",
    description: "Turns messy property notes into comparable structured attributes.",
    inputSchema: "Raw property record",
    outputSchema: "Normalized area, budget band, amenities, caveats",
    promptSummary: "Extract location, type, commercial facts, lifestyle signals, and missing data.",
    x: 40,
    y: 100,
  },
  {
    id: "mod_source_scout",
    key: "source-scout",
    label: "Source Scout",
    description: "Chooses enabled Kottayam source URLs and run parameters.",
    inputSchema: "Enabled scrape sources + district scope",
    outputSchema: "Source run plan",
    promptSummary: "Keep the run public-page only and scoped to Kottayam district.",
    x: 40,
    y: 520,
  },
  {
    id: "mod_scraper_adapters",
    key: "scraper-adapters",
    label: "Scraper Adapters",
    description: "Runs source-specific Playwright adapters and captures raw cards.",
    inputSchema: "Source run plan",
    outputSchema: "Raw plot, lead, and reference candidates",
    promptSummary: "Each source fails independently and never bypasses login/CAPTCHA/contact gates.",
    x: 340,
    y: 520,
  },
  {
    id: "mod_plot_normalizer",
    key: "plot-normalizer",
    label: "Plot Normalizer",
    description: "Extracts land-specific facts from raw Kottayam plot text.",
    inputSchema: "Raw listing card",
    outputSchema: "Area, unit, price, locality, road/access notes",
    promptSummary: "Normalize Kerala plot units like cents, acres, and sqft.",
    x: 650,
    y: 500,
  },
  {
    id: "mod_lead_normalizer",
    key: "lead-normalizer",
    label: "Lead Normalizer",
    description: "Extracts buyer or broker demand from public demand text.",
    inputSchema: "Raw demand card",
    outputSchema: "Preferred areas, budget, purpose, visible public contact",
    promptSummary: "Never invent contact info; keep only visibly public details.",
    x: 650,
    y: 650,
  },
  {
    id: "mod_duplicate_resolver",
    key: "duplicate-resolver",
    label: "Duplicate Resolver",
    description: "Flags repeated scraped items before review/import.",
    inputSchema: "Normalized scraped candidate + existing records",
    outputSchema: "Review, duplicate, or rejected status suggestion",
    promptSummary: "Compare source URL, locality, title, price, and plot size.",
    x: 960,
    y: 570,
  },
  {
    id: "mod_review_gate",
    key: "review-gate",
    label: "Review Gate",
    description: "Requires approval before scraped records become properties or leads.",
    inputSchema: "Normalized candidate",
    outputSchema: "Imported property/client or rejected candidate",
    promptSummary: "No scraped item enters matching until human-approved.",
    x: 1260,
    y: 570,
  },
  {
    id: "mod_client_normalizer",
    key: "client-normalizer",
    label: "Client Preference Normalizer",
    description: "Converts client notes into constraints, preferences, and deal risks.",
    inputSchema: "Client profile and notes",
    outputSchema: "Budget, preferred areas, must-haves, blockers, urgency",
    promptSummary: "Separate hard constraints from soft preferences and infer open questions.",
    x: 40,
    y: 300,
  },
  {
    id: "mod_rule_matcher",
    key: "rule-matcher",
    label: "Rule Matcher",
    description: "Applies deterministic budget, area, type, bedroom, and size filters.",
    inputSchema: "Normalized property + normalized client",
    outputSchema: "Pass/fail, score baseline, reasons, warnings",
    promptSummary: "No LLM. This module keeps matching grounded in explicit facts.",
    x: 340,
    y: 200,
  },
  {
    id: "mod_fit_analyst",
    key: "fit-analyst",
    label: "Fit Analyst",
    description: "Explains why a passing match is compelling or weak.",
    inputSchema: "Rule match result plus source records",
    outputSchema: "Fit summary, confidence, buying angle",
    promptSummary: "Write a concise advisor-style explanation for a real estate operator.",
    x: 650,
    y: 120,
  },
  {
    id: "mod_objection_finder",
    key: "objection-finder",
    label: "Objection Finder",
    description: "Surfaces likely objections before outreach.",
    inputSchema: "Fit analysis and raw notes",
    outputSchema: "Objection list and questions to clarify",
    promptSummary: "Look for budget stretch, location mismatch, missing amenities, and timing risk.",
    x: 650,
    y: 310,
  },
  {
    id: "mod_draft_writer",
    key: "draft-writer",
    label: "Outreach Draft Writer",
    description: "Creates a human-approved WhatsApp/email/call draft.",
    inputSchema: "Match, fit summary, objections",
    outputSchema: "Draft copy and suggested tone",
    promptSummary: "Draft only. Never claim a message was sent.",
    x: 960,
    y: 190,
  },
  {
    id: "mod_approval_gate",
    key: "approval-gate",
    label: "Approval Gate",
    description: "Requires your review before anything leaves the system.",
    inputSchema: "Draft message",
    outputSchema: "Pending, approved, rejected, or edited",
    promptSummary: "Human approval is mandatory for every outbound action.",
    x: 1260,
    y: 190,
  },
  {
    id: "mod_reporter",
    key: "run-reporter",
    label: "Run Reporter",
    description: "Persists run logs, step outputs, and audit trail.",
    inputSchema: "All module results",
    outputSchema: "Run summary and trace",
    promptSummary: "Summarize what happened and preserve enough context to debug it.",
    x: 1560,
    y: 190,
  },
];

export const realEstateEdges: AgentEdge[] = [
  { id: "edge_property_rule", source: "mod_property_normalizer", target: "mod_rule_matcher", label: "property facts" },
  { id: "edge_client_rule", source: "mod_client_normalizer", target: "mod_rule_matcher", label: "client constraints" },
  { id: "edge_rule_fit", source: "mod_rule_matcher", target: "mod_fit_analyst", label: "passed candidates" },
  { id: "edge_rule_objections", source: "mod_rule_matcher", target: "mod_objection_finder", label: "warnings" },
  { id: "edge_fit_draft", source: "mod_fit_analyst", target: "mod_draft_writer", label: "positioning" },
  { id: "edge_objection_draft", source: "mod_objection_finder", target: "mod_draft_writer", label: "risks" },
  { id: "edge_draft_approval", source: "mod_draft_writer", target: "mod_approval_gate", label: "draft" },
  { id: "edge_approval_report", source: "mod_approval_gate", target: "mod_reporter", label: "audit event" },
  { id: "edge_source_adapters", source: "mod_source_scout", target: "mod_scraper_adapters", label: "run plan" },
  { id: "edge_adapter_plot", source: "mod_scraper_adapters", target: "mod_plot_normalizer", label: "raw plots" },
  { id: "edge_adapter_lead", source: "mod_scraper_adapters", target: "mod_lead_normalizer", label: "raw demand" },
  { id: "edge_plot_duplicate", source: "mod_plot_normalizer", target: "mod_duplicate_resolver", label: "normalized plot" },
  { id: "edge_lead_duplicate", source: "mod_lead_normalizer", target: "mod_duplicate_resolver", label: "normalized lead" },
  { id: "edge_duplicate_review", source: "mod_duplicate_resolver", target: "mod_review_gate", label: "review item" },
  { id: "edge_review_match", source: "mod_review_gate", target: "mod_rule_matcher", label: "approved records" },
];

export const kottayamScrapeSources: ScrapeSource[] = [
  {
    id: "src_magicbricks_kottayam_plots",
    key: "magicbricks-kottayam-plots",
    name: "MagicBricks Kottayam plots",
    kind: "property",
    baseUrl: "https://www.magicbricks.com",
    searchUrl: "https://www.magicbricks.com/residential-plots-land-for-sale-in-kottayam-pppfs",
    enabled: true,
    notes: "Public Kottayam residential plot listing page. Contact capture is visible-public only.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "src_housing_kottayam_plots",
    key: "housing-kottayam-plots",
    name: "Housing Kottayam plots",
    kind: "property",
    baseUrl: "https://housing.com",
    searchUrl: "https://housing.com/in/buy/kottayam/plots-fid/",
    enabled: true,
    notes: "Public Kottayam plots page.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "src_olx_kottayam_land",
    key: "olx-kottayam-land",
    name: "OLX Kottayam land",
    kind: "property",
    baseUrl: "https://www.olx.in",
    searchUrl: "https://www.olx.in/en-in/kottayam_g4058873/lands-plots_c1729",
    enabled: true,
    notes: "Public OLX land/plot listings for Kottayam district.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "src_99acres_kottayam_plots",
    key: "99acres-kottayam-plots",
    name: "99acres Kottayam plots",
    kind: "property",
    baseUrl: "https://www.99acres.com",
    searchUrl: "https://www.99acres.com/residential-land-in-kottayam-ffid",
    enabled: true,
    notes: "Public 99acres plot search; adapter records source failures instead of forcing import.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "src_nobroker_kottayam_plots",
    key: "nobroker-kottayam-plots",
    name: "NoBroker Kottayam plots",
    kind: "property",
    baseUrl: "https://www.nobroker.in",
    searchUrl: "https://www.nobroker.in/property/sale/land/kottayam",
    enabled: true,
    notes: "Public NoBroker-style search URL; may return sparse or blocked data.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "src_keralarealty_kottayam_land",
    key: "keralarealty-kottayam-land",
    name: "KeralaRealty Kottayam land",
    kind: "property",
    baseUrl: "https://www.keralarealty.com",
    searchUrl: "https://www.keralarealty.com/listings/?location=kottayam&property-type=land",
    enabled: true,
    notes: "Kerala-focused listing source.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "src_kerala_rera",
    key: "kerala-rera-reference",
    name: "Kerala RERA reference",
    kind: "reference",
    baseUrl: "https://rera.kerala.gov.in",
    searchUrl: "https://rera.kerala.gov.in/",
    enabled: true,
    notes: "Reference/verification source only; not the primary inventory source.",
    createdAt: now,
    updatedAt: now,
  },
];

export const seedData: PlotverseData = {
  properties: [],
  clients: [],
  matches: [],
  draftMessages: [],
  agentModules: realEstateModules,
  agentEdges: realEstateEdges,
  agentRuns: [],
  agentRunSteps: [],
  csvImports: [],
  scrapeSources: kottayamScrapeSources,
  scrapeRuns: [],
  scrapeItems: [],
  tokenUsageEvents: [],
};
